name: NodeJS with Webpack

on:
        push:
                branches: ['main']
        pull_request:
                branches: ['main']

jobs:
        build:
                runs-on: ubuntu-latest

                strategy:
                        matrix:
                                node-version: [18.x, 20.x, 22.x]

                steps:
                        - uses: actions/checkout@v4

                        - name: Use Node.js ${{ matrix.node-version }}
                          uses: actions/setup-node@v4
                          with:
                                  node-version: ${{ matrix.node-version }}

                        - name: Install System Dependencies
                          run: sudo apt-get install ffmpeg

                        - name: Install Node.js Dependencies
                          run: |
                                  npm install 
                                  npm install utf-8-validate bufferutil rimraf@latest glob@latest puppeteer@latest whatsapp-web.js@latest

                        - name: Fix Vulnerabilities
                          run: npm audit fix --force

                        - name: Clean Directories
                          run: |
                                  rm -rf ./public ./dist .wwebjs_auth .wwebjs_cache

                        - name: Compile TypeScript
                          run: npx tsc

                        - name: Run Webpack
                          run: webpack --config webpack.config.js

                        - name: Fix Vulnerabilities
                          run: npm audit fix --force
